/* timeline.js
 * Canonical renderer. Copy this file unchanged.
 * Do not rewrite stacking, scales, or collision tests.
 * Playground vs product is body class "playground", not a flag in this file.
 */
    (function () {
      'use strict';

      /*
       * Do not edit this file. Product vs playground is body.playground.
       * Data is the HTML table; this script only paints the axis.
       */
      const PLAYGROUND = document.body.classList.contains('playground');

      const SEC = 1;
      const MIN = 60 * SEC;
      const HOUR = 60 * MIN;
      const DAY = 24 * HOUR;
      const YEAR = 365.25 * DAY;
      const KYR = 1e3 * YEAR;
      const MYR = 1e6 * YEAR;
      const GYR = 1e9 * YEAR;
      const PLANCK = 5.391247e-44; // seconds

      const MONTHS_SHORT = [
        'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
      ];

      /*
       * Named resolutions: how wide is the interval an event is known to fall
       * within. `seconds` is an additive width, converted into the axis's own
       * units. `factor` is a multiplicative width for logarithmic axes, where
       * 10x is one order of magnitude.
       */
      const RESOLUTIONS = {
        exact: { seconds: 0 },
        second: { seconds: SEC },
        minute: { seconds: MIN },
        hour: { seconds: HOUR },
        day: { seconds: DAY },
        week: { seconds: 7 * DAY },
        month: { seconds: 30.44 * DAY },
        year: { seconds: YEAR },
        decade: { seconds: 10 * YEAR },
        century: { seconds: 100 * YEAR },
        millennium: { seconds: 1000 * YEAR },
        myr: { seconds: MYR },
        '10myr': { seconds: 10 * MYR },
        '100myr': { seconds: 100 * MYR },
        gyr: { seconds: GYR },
        order: { factor: 10 },
        '3orders': { factor: 1000 }
      };

      // Horizontal
      const LABEL_OFFSET = 6;
      const RESERVE_PADDING = 14;
      const MIN_HAIRLINE_GAP = 1;
      const HAIRLINE_WIDTH = 1;
      const MIN_WIDTH_SLACK = 8;
      const SAME_DAY_NUDGE = 3;
      const MAX_LABEL_WIDTH = 1000;
      const MAX_LABEL_VIEWPORT_RATIO = 0.95;

      // Vertical
      const BASE_TOP = 24;
      const STACK_STEP = 4;
      const TEXT_MARGIN = 10;
      const MAX_STACK_ATTEMPTS = 120;
      const MAX_RETAINED_WIDTH_DELTA = 80;
      const MIN_HAIRLINE_HEIGHT = 10;
      const MIN_TIMELINE_HEIGHT = 160;
      const HEIGHT_PADDING = 24;

      // Hierarchical scale grid
      const SCALE_CELL_PAD = 10;          // padding + breathing room inside a cell
      const SCALE_ROW_HEIGHT = 23.2;      // matches .scale-row height (~1.45rem)
      const SCALE_NUMBER_STEPS = [1, 2, 3, 6, null];

      const DATASET_ORDER = ['cuban', 'sprint', 'civilisation', 'earth', 'universe'];
      const UNIT_SECONDS = { hour: HOUR, year: YEAR, Myr: MYR };
      let DATASETS = {};

      const timeline = document.getElementById('timeline');
      const axis = timeline.querySelector('.axis');
      const scaleGrid = document.getElementById('scaleGrid');
      const periodLabelMeasure = document.getElementById('periodLabelMeasure');
      const pageTitle = document.getElementById('pageTitle');
      const pageSubtitle = document.getElementById('pageSubtitle');
      const datasetRadios = Array.from(document.querySelectorAll('input[name="dataset"]'));
      const timelineSlot = document.querySelector('.timeline-slot');
      const timelineWrapper = document.querySelector('.timeline-wrapper');
      const controls = {
        attachSide: document.getElementById('attachSide'),
        fullWidth: document.getElementById('fullWidth'),
        width: document.getElementById('timelineWidth'),
        widthValue: document.getElementById('widthValue'),
        labelWidth: document.getElementById('labelWidth'),
        labelWidthValue: document.getElementById('labelWidthValue'),
        extendTimeline: document.getElementById('extendTimeline'),
        periodsPlacement: document.getElementById('periodsPlacement')
      };
      const controlsPanel = document.getElementById('controls');
      const minimiseControls = document.getElementById('minimiseControls');
      const flagsFab = document.getElementById('flagsFab');
      const CONTROLS_MINIMISED_KEY = 'timeline.controlsMinimised';

      let active = null;
      let events = [];
      const stackRows = new Map();
      let previousAttachLeft = null;
      let previousDescs = null;
      let previousWidth = null;
      let previousLabelWidth = null;
      let previousExtend = null;
      let previousPeriodsPlacement = null;
      let previousDatasetId = null;

      /*
       * The full-bleed wrapper is sized from the visible page width so it never
       * reaches under a vertical scrollbar and scrolls the page sideways.
       */
      function syncViewportWidth() {
        timelineWrapper.style.setProperty(
          '--viewport-width',
          document.documentElement.clientWidth + 'px'
        );
      }

      function availableWidth() {
        syncViewportWidth();
        return timeline.parentElement.clientWidth;
      }

      function syncWidthControl(fullWidth) {
        const available = availableWidth();
        const minimumWidth = parseInt(controls.width.min, 10);
        const width = Math.max(minimumWidth, available);

        controls.width.max = Math.max(parseInt(controls.width.max, 10), width);
        controls.width.disabled = fullWidth;

        if (fullWidth) {
          controls.width.value = width;
        }

        return parseInt(controls.width.value, 10);
      }

      function readControls() {
        const fullWidth = controls.fullWidth.checked;
        return {
          columnsKey: visibleContentCols(active && active.section ? active.section : document.querySelector('.timeline-source')).join(','),
          attachLeft: controls.attachSide.value === 'left',
          fullWidth,
          width: syncWidthControl(fullWidth),
          margin: TEXT_MARGIN,
          labelWidth: parseInt(controls.labelWidth.value, 10),
          extendTimeline: controls.extendTimeline.checked,
          periodsPlacement: controls.periodsPlacement.value
        };
      }

      function escapeHtml(s) {
        return String(s)
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;');
      }

      function clamp(value, min, max) {
        return Math.min(max, Math.max(min, value));
      }

      function eventFraction(value) {
        const scale = active.scale;
        if (scale.kind === 'calendar-days') {
          return clamp(value / scale.totalDays, 0, 1);
        }
        if (scale.kind === 'linear-units') {
          return clamp((value - scale.start) / (scale.end - scale.start), 0, 1);
        }
        // log-seconds
        const t = Math.max(value, scale.tMin);
        return clamp(
          Math.log(t / scale.tMin) / Math.log(scale.tMax / scale.tMin),
          0,
          1
        );
      }

      function timeFromFraction(fraction) {
        const scale = active.scale;
        if (scale.kind === 'calendar-days') {
          return fraction * scale.totalDays;
        }
        if (scale.kind === 'linear-units') {
          return scale.start + fraction * (scale.end - scale.start);
        }
        return scale.tMin * Math.pow(scale.tMax / scale.tMin, fraction);
      }

      function formatDuration(seconds) {
        const abs = Math.abs(seconds);
        if (abs <= PLANCK * 2) return 'tₚ';
        if (abs < 1e-6) return '10' + toSuperscript(Math.round(Math.log10(abs))) + ' s';
        if (abs < 1e-3) return (abs * 1e6).toFixed(abs * 1e6 < 10 ? 1 : 0) + ' µs';
        if (abs < 1) return (abs * 1e3).toFixed(abs * 1e3 < 10 ? 1 : 0) + ' ms';
        if (abs < MIN) return abs.toFixed(abs < 10 ? 1 : 0) + ' s';
        if (abs < HOUR) return (abs / MIN).toFixed(0) + ' min';
        if (abs < DAY) return (abs / HOUR).toFixed(0) + ' h';
        if (abs < YEAR) return (abs / DAY).toFixed(0) + ' d';
        if (abs < KYR) return (abs / YEAR).toFixed(abs / YEAR < 10 ? 1 : 0) + ' yr';
        if (abs < MYR) return (abs / KYR).toFixed(abs / KYR < 10 ? 1 : 0) + ' kyr';
        if (abs < GYR) return (abs / MYR).toFixed(abs / MYR < 10 ? 1 : 0) + ' Myr';
        if (abs < 1e6 * GYR) return (abs / GYR).toFixed(abs / GYR < 10 ? 1 : 0) + ' Gyr';
        return '10' + toSuperscript(Math.round(Math.log10(abs / YEAR))) + ' yr';
      }

      function toSuperscript(n) {
        const map = {
          '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴',
          '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹', '-': '⁻'
        };
        return String(n).split('').map(function (ch) { return map[ch] || ch; }).join('');
      }

      function tickFormatNamed(name, scale) {
        if (name === 'round') {
          return function (v) { return String(Math.round(v)); };
        }
        if (name === 'yearCe') {
          return function (v) {
            if (v < 0) return Math.abs(Math.round(v)) + ' BCE';
            return String(Math.round(v));
          };
        }
        if (name === 'myrAgo') {
          return function (v) {
            const ago = scale.end - v;
            if (ago <= 0) return 'now';
            if (ago >= 1000) {
              return (ago / 1000).toFixed(ago % 1000 === 0 ? 0 : 1) + ' Ga';
            }
            return Math.round(ago) + ' Ma';
          };
        }
        return function (v) { return String(v); };
      }

      function parseLocalDate(iso) {
        const s = String(iso).trim();
        const m = s.match(/^(-?\d{1,6})(?:-(\d{2})(?:-(\d{2})(?:T(\d{2})(?::(\d{2})(?::(\d{2}(?:\.\d+)?))?)?)?)?)?$/);
        if (!m) return null;
        const year = parseInt(m[1], 10);
        const month = m[2] != null ? parseInt(m[2], 10) - 1 : 0;
        const day = m[3] != null ? parseInt(m[3], 10) : 1;
        const hour = m[4] != null ? parseInt(m[4], 10) : 0;
        const min = m[5] != null ? parseInt(m[5], 10) : 0;
        const sec = m[6] != null ? parseFloat(m[6]) : 0;
        const precision = m[6] != null ? 'second' : m[5] != null ? 'minute' : m[4] != null ? 'hour' : m[3] != null ? 'day' : m[2] != null ? 'month' : 'year';
        return {
          date: new Date(year, month, day, hour, min, Math.floor(sec)),
          year: year,
          precision: precision,
          hour: hour,
          minute: min
        };
      }

      function isoToAxis(iso, scale) {
        const parsed = parseLocalDate(iso);
        if (!parsed) return NaN;
        if (scale.kind === 'calendar-days') {
          const ms = parsed.date.getTime() - scale.origin.getTime();
          return ms / (DAY * 1000);
        }
        if (scale.kind === 'linear-units' && scale.unit === 'hour') {
          return (parsed.date.getTime() - scale.origin.getTime()) / (HOUR * 1000);
        }
        if (scale.kind === 'linear-units' && scale.unit === 'year') {
          return parsed.year + (scale.unit === 'year' ? 0 : 0);
        }
        return parsed.year;
      }

      function visibleContentCols(section) {
        return Array.from(section.querySelectorAll('.col-toggles input[data-col]:checked'))
          .map(function (el) { return parseInt(el.getAttribute('data-col'), 10); })
          .filter(function (n) { return n >= 2; })
          .sort(function (a, b) { return a - b; });
      }

      function cellText(row, index) {
        const cell = row.children[index];
        return cell ? cell.textContent.trim() : '';
      }

      function parseTimeCell(td, scale) {
        const el = td.querySelector('time') || td;
        const iso = (el.getAttribute('datetime') || td.textContent || '').trim();
        const dataAt = el.getAttribute('data-at');
        const dataEnd = el.getAttribute('data-end-at');
        const dataRes = el.getAttribute('data-resolution');
        const date = iso || td.textContent.trim();
        const result = { date: date, resolution: dataRes || undefined, time: null, endAt: null };

        if (dataAt != null && dataAt !== '') {
          result.at = parseFloat(dataAt);
          if (dataEnd != null && dataEnd !== '') result.endAt = parseFloat(dataEnd);
          return result;
        }

        const parts = iso.split('/');
        if (parts.length === 2 && parts[0] && parts[1]) {
          result.at = isoToAxis(parts[0], scale);
          result.endAt = isoToAxis(parts[1], scale);
          return result;
        }

        const parsed = parseLocalDate(iso);
        if (!parsed) {
          result.at = parseFloat(iso);
          return result;
        }
        result.at = isoToAxis(iso, scale);
        result.resolution = dataRes || parsed.precision;
        if (scale.kind === 'calendar-days' && (parsed.precision === 'hour' || parsed.precision === 'minute' || parsed.precision === 'second')) {
          result.time = parsed.hour + parsed.minute / 60;
          result.at = Math.floor(result.at);
        }
        return result;
      }

      function parseScale(table, section) {
        const d = table.dataset;
        const kind = d.kind;
        const scale = {
          kind: kind,
          baseResolution: d.baseResolution || 'day',
          periodLabel: d.periodLabel,
          summary: d.summary
        };
        if (kind === 'calendar-days') {
          scale.origin = new Date(d.origin + (d.origin.indexOf('T') === -1 ? 'T00:00:00' : ''));
          const end = new Date(d.end + (d.end.indexOf('T') === -1 ? 'T00:00:00' : ''));
          scale.totalDays = (end.getTime() - scale.origin.getTime()) / (DAY * 1000);
        } else if (kind === 'linear-units') {
          scale.unit = d.unit;
          scale.secondsPerUnit = UNIT_SECONDS[d.unit];
          if (d.origin) {
            scale.origin = new Date(d.origin);
          }
          if (d.start != null && d.start !== '') scale.start = parseFloat(d.start);
          if (d.end) {
            if (d.origin && d.unit === 'hour') {
              scale.start = scale.start != null ? scale.start : 0;
              scale.end = (new Date(d.end).getTime() - scale.origin.getTime()) / (HOUR * 1000);
            } else if (d.start != null && d.start !== '' && /^\-?\d+(\.\d+)?$/.test(d.end)) {
              scale.end = parseFloat(d.end);
            } else if (d.origin && kind === 'linear-units') {
              scale.end = parseFloat(d.end);
            } else {
              scale.end = parseFloat(d.end);
            }
          }
          if (d.tickFormat) scale.tickFormat = tickFormatNamed(d.tickFormat, scale);
        } else if (kind === 'log-seconds') {
          scale.tMin = parseFloat(d.tMin);
          scale.tMax = parseFloat(d.tMax);
          scale.eras = Array.from(section.querySelectorAll('.timeline-eras li')).map(function (li) {
            return {
              t0: parseFloat(li.getAttribute('data-t0')),
              t1: parseFloat(li.getAttribute('data-t1')),
              label: li.textContent.trim()
            };
          });
        }
        return scale;
      }

      function parseDataset(section) {
        const table = section.querySelector('.timeline-data');
        const caption = table.querySelector('caption');
        const sub = caption && caption.querySelector('.caption-sub');
        const title = caption ? Array.from(caption.childNodes).filter(function (n) {
          return n.nodeType === 3;
        }).map(function (n) { return n.textContent.trim(); }).join(' ').trim() : section.dataset.id;
        const scale = parseScale(table, section);
        const cols = visibleContentCols(section);
        const events = Array.from(table.tBodies[0].rows).map(function (row, i) {
          const timed = parseTimeCell(row.cells[0], scale);
          const content = cols.map(function (c) { return cellText(row, c - 1); }).filter(Boolean);
          return {
            id: row.id || section.dataset.id + '-' + (i + 1),
            at: timed.at,
            endAt: timed.endAt,
            time: timed.time,
            resolution: timed.resolution,
            title: content[0] || '',
            desc: content.slice(1).join(' '),
            date: timed.date
          };
        });
        const radio = document.querySelector('input[name="dataset"][value="' + section.dataset.id + '"]');
        return {
          id: section.dataset.id,
          name: radio ? radio.parentNode.textContent.trim() : title,
          title: title,
          subtitle: sub ? sub.textContent.trim() : '',
          scale: scale,
          events: events,
          section: section
        };
      }

      function selectedDatasetId() {
        const checked = document.querySelector('input[name="dataset"]:checked');
        if (checked) return checked.value;
        const first = document.querySelector('.timeline-source');
        return first ? first.dataset.id : DATASET_ORDER[0];
      }

      function loadDatasetsFromDom() {
        DATASETS = {};
        Array.from(document.querySelectorAll('.timeline-source')).forEach(function (section) {
          DATASETS[section.dataset.id] = parseDataset(section);
        });
      }

      function axisDomain(scale) {
        if (scale.kind === 'calendar-days') return { min: 0, max: scale.totalDays };
        if (scale.kind === 'linear-units') return { min: scale.start, max: scale.end };
        return { min: scale.tMin, max: scale.tMax };
      }

      // Seconds in one step of the axis's own numbering.
      function axisUnitSeconds(scale) {
        if (scale.kind === 'calendar-days') return DAY;
        if (scale.kind === 'linear-units') return scale.secondsPerUnit;
        return SEC;
      }

      // 'HH:MM' or hours as a number, as a 0–1 position through the day.
      function dayFractionFromTime(time) {
        let hours;
        if (typeof time === 'number') {
          hours = time;
        } else {
          const parts = String(time).split(':');
          hours = (parseFloat(parts[0]) || 0) + (parseFloat(parts[1]) || 0) / 60;
        }
        return clamp(hours / 24, 0, 1);
      }

      function intervalEnd(start, resolution, scale) {
        if (typeof resolution === 'number') return start + resolution;

        const span = RESOLUTIONS[resolution] || RESOLUTIONS.exact;
        if (span.factor !== undefined) return start * span.factor;
        return start + span.seconds / axisUnitSeconds(scale);
      }

      /*
       * An event's stored `at` names the START of the interval it is known to
       * fall within; `resolution` gives that interval's width. The hairline goes
       * at the centre of the interval, because the true instant inside it is
       * unknown — so a day-only event sits at midday, and stating a finer
       * resolution narrows the interval and moves the hairline. `exact` means a
       * zero-width interval and is used unchanged.
       *
       * The axis bounds the interval: nothing is known beyond what is shown, so
       * an interval running past either end is truncated there.
       */
      function resolveAt(data, scale) {
        const domain = axisDomain(scale);
        let start = data.at;
        if (scale.kind === 'calendar-days' && data.time != null) {
          start += dayFractionFromTime(data.time);
        }
        start = clamp(start, domain.min, domain.max);

        if (data.endAt != null && Number.isFinite(data.endAt)) {
          const end = clamp(data.endAt, start, domain.max);
          if (end === start) return start;
          if (scale.kind === 'log-seconds' && start > 0) return Math.sqrt(start * end);
          return (start + end) / 2;
        }

        const resolution = data.resolution !== undefined
          ? data.resolution
          : (data.time != null ? 'hour' : scale.baseResolution);

        const end = clamp(intervalEnd(start, resolution, scale), start, domain.max);
        if (end === start) return start;

        /*
         * A log axis maps ratios to distance, so the visually centred point of
         * an interval is its geometric mean. The arithmetic mean of a one-decade
         * interval sits 74% of the way across it, not 50%.
         */
        if (scale.kind === 'log-seconds' && start > 0) return Math.sqrt(start * end);
        return (start + end) / 2;
      }

      function loadDataset(id) {
        loadDatasetsFromDom();
        active = DATASETS[id] || DATASETS[DATASET_ORDER[0]] || DATASETS[Object.keys(DATASETS)[0]];
        const radio = document.querySelector('input[name="dataset"][value="' + active.id + '"]');
        if (radio) radio.checked = true;
        pageTitle.textContent = active.title;
        pageSubtitle.textContent = active.subtitle;
        document.title = active.title + ' — Adaptive Timeline';

        timeline.querySelectorAll('.event').forEach(function (el) { el.remove(); });
        stackRows.clear();
        previousDatasetId = null;

        active.events.forEach(function (data) {
          const ev = document.createElement('div');
          ev.className = 'event';
          ev.dataset.id = data.id;
          ev.dataset.at = String(resolveAt(data, active.scale));
          ev.innerHTML = '<div class="hairline"></div><div class="label"></div>';
          timeline.appendChild(ev);
        });

        events = Array.from(timeline.querySelectorAll('.event'));
      }

      function rectsOverlap(a, b) {
        return !(
          a.right <= b.left ||
          a.left >= b.right ||
          a.bottom <= b.top ||
          a.top >= b.bottom
        );
      }

      function labelRect(item, top, attachLeft) {
        const left = attachLeft
          ? item.x - LABEL_OFFSET - item.width
          : item.x + LABEL_OFFSET;
        return { left: left, right: left + item.width, top: top, bottom: top + item.height };
      }

      function attachLabel(label, attachLeft) {
        label.style.left = attachLeft ? 'auto' : LABEL_OFFSET + 'px';
        label.style.right = attachLeft ? LABEL_OFFSET + 'px' : 'auto';
        label.style.textAlign = attachLeft ? 'right' : 'left';
      }

      function eventData(id) {
        for (let i = 0; i < active.events.length; i++) {
          if (active.events[i].id === id) return active.events[i];
        }
        return null;
      }

      function renderLabels() {
        events.forEach(function (ev) {
          const data = eventData(ev.dataset.id);
          if (!data) return;

          const label = ev.querySelector('.label');
          const parts = [escapeHtml(data.title)];
          if (data.desc) {
            parts.push('<span class="desc">' + escapeHtml(data.desc) + '</span>');
          }
          parts.push('<span class="date">' + escapeHtml(data.date) + '</span>');

          label.style.whiteSpace = 'normal';
          label.innerHTML = parts.join('\n');
        });
      }

      function measureLabels(attachLeft, labelWidth) {
        const maxWidth = Math.min(
          labelWidth,
          MAX_LABEL_WIDTH,
          Math.round(window.innerWidth * MAX_LABEL_VIEWPORT_RATIO)
        );

        return events
          .map(function (ev) {
            const label = ev.querySelector('.label');
            attachLabel(label, attachLeft);
            label.style.width = 'max-content';
            label.style.maxWidth = maxWidth + 'px';
            const at = parseFloat(ev.dataset.at);
            return {
              ev: ev,
              label: label,
              hairline: ev.querySelector('.hairline'),
              at: at,
              fraction: eventFraction(at),
              width: label.offsetWidth,
              height: label.offsetHeight,
              x: 0
            };
          })
          .sort(function (a, b) { return a.fraction - b.fraction; });
      }

      function positionHairlines(items, usable, offset) {
        let lastX = -Infinity;
        let lastKey = null;
        let sameCount = 0;
        // Leave room for the line's own width so an event at the end of the
        // axis does not sit a pixel past it.
        const span = Math.max(usable - HAIRLINE_WIDTH, 0);

        items.forEach(function (item) {
          let x = item.fraction * span;
          const key = String(item.at);

          if (key === lastKey) {
            sameCount++;
            x += sameCount * SAME_DAY_NUDGE;
          } else {
            sameCount = 0;
          }

          if (x < lastX + MIN_HAIRLINE_GAP) x = lastX + MIN_HAIRLINE_GAP;

          lastX = x;
          lastKey = key;

          // Nudging and gap enforcement can push a trailing cluster past the
          // axis; the last events share its end rather than overflow.
          item.x = Math.round(Math.min(x, span) + offset);
          item.ev.style.left = item.x + 'px';
        });
      }

      function constrainLabelWidths(items, labelWidth) {
        const maxWidth = Math.min(
          labelWidth,
          MAX_LABEL_WIDTH,
          Math.round(window.innerWidth * MAX_LABEL_VIEWPORT_RATIO)
        );

        items.forEach(function (item) {
          item.label.style.width = 'max-content';
          item.label.style.maxWidth = maxWidth + 'px';
          item.width = item.label.offsetWidth || 80;
          item.height = item.label.offsetHeight || 20;
        });
      }

      function findFreeRow(item, placed, attachLeft, margin, labelBaseTop) {
        const previousRow = stackRows.get(item.ev.dataset.id);
        const firstRow = previousRow === undefined ? 0 : previousRow;
        const rowStep = STACK_STEP + margin;
        const baseTop = labelBaseTop;

        for (let attempt = 0; attempt < MAX_STACK_ATTEMPTS; attempt++) {
          const row = firstRow + attempt;
          const top = baseTop + row * rowStep;
          const candidate = labelRect(item, top, attachLeft);
          if (!placed.some(function (rect) { return rectsOverlap(candidate, rect); })) {
            stackRows.set(item.ev.dataset.id, row);
            return { row: row, top: top };
          }
        }

        const row = firstRow + MAX_STACK_ATTEMPTS;
        stackRows.set(item.ev.dataset.id, row);
        return { row: row, top: baseTop + row * rowStep };
      }

      function stackLabels(items, attachLeft, margin, labelBaseTop) {
        const order = attachLeft ? items : items.slice().reverse();
        const placed = [];
        let maxBottom = 0;

        order.forEach(function (item) {
          const found = findFreeRow(item, placed, attachLeft, margin, labelBaseTop);
          const rect = labelRect(item, found.top, attachLeft);

          item.label.style.top = found.top + 'px';
          attachLabel(item.label, attachLeft);
          item.hairline.style.height = Math.max(
            MIN_HAIRLINE_HEIGHT,
            found.top + item.height
          ) + 'px';

          placed.push(rect);
          maxBottom = Math.max(maxBottom, rect.bottom);
        });

        return maxBottom;
      }

      /*
       * Smallest reserve that still keeps every label inside the timeline.
       *
       * The default band is as wide as the widest label, but only events sitting
       * near the attachment edge actually need that much room — further along the
       * axis a label already has the axis itself to sit over. For an event at
       * fraction `far` from the reserved edge the label needs
       *   need <= far * total + (1 - far) * reserve
       * which rearranges to the per-event minimum below. The widest requirement
       * wins, and the result can never exceed the unextended band.
       */
      function fittedReserve(items, total, attachLeft, baseReserve) {
        let required = 0;

        items.forEach(function (item) {
          const far = attachLeft ? item.fraction : 1 - item.fraction;
          // An unplaceable event says nothing about the band it needs.
          if (!Number.isFinite(far) || !Number.isFinite(item.width)) return;
          if (1 - far < 1e-6) return;
          const need = item.width + LABEL_OFFSET + RESERVE_PADDING;
          required = Math.max(required, (need - far * total) / (1 - far));
        });

        return clamp(Math.ceil(required), 0, baseReserve);
      }

      function layoutAxis(reserve, attachLeft) {
        axis.style.left = attachLeft ? reserve + 'px' : '0';
        axis.style.right = attachLeft ? '0' : reserve + 'px';
      }

      function measurePeriodText(text, heavy) {
        periodLabelMeasure.textContent = text;
        periodLabelMeasure.style.fontWeight = heavy ? '600' : '400';
        return periodLabelMeasure.offsetWidth;
      }

      function dateAtDay(day) {
        const date = new Date(active.scale.origin.getTime());
        date.setDate(active.scale.origin.getDate() + day);
        return date;
      }

      function cellFits(cell, usable) {
        const width = (cell.end - cell.start) * usable;
        return measurePeriodText(cell.label) + SCALE_CELL_PAD <= width;
      }

      function rowFits(cells, usable) {
        return cells.length > 0 && cells.every(function (cell) {
          return cellFits(cell, usable);
        });
      }

      // Keep cells that can show their label; stretch neighbours across gaps.
      function packCells(cells, usable) {
        if (!cells.length) return [];
        const kept = [];

        cells.forEach(function (cell) {
          if (!cellFits(cell, usable)) {
            if (kept.length) kept[kept.length - 1].end = cell.end;
            return;
          }
          if (kept.length) kept[kept.length - 1].end = cell.start;
          kept.push({
            start: cell.start,
            end: cell.end,
            label: cell.label
          });
        });

        if (kept.length) {
          kept[0].start = cells[0].start;
          kept[kept.length - 1].end = cells[cells.length - 1].end;
        }
        return kept;
      }

      function groupCalendarBands(keyFn, labelFn) {
        const totalDays = active.scale.totalDays;
        const groups = [];
        let current = null;

        for (let day = 0; day <= totalDays; day++) {
          const date = dateAtDay(day);
          const key = keyFn(date);
          if (!current || current.key !== key) {
            if (current) groups.push(current);
            current = { key: key, startDay: day, label: labelFn(date) };
          }
        }
        if (current) groups.push(current);

        return groups.map(function (group, index) {
          const next = groups[index + 1];
          return {
            start: group.startDay / totalDays,
            end: next ? next.startDay / totalDays : 1,
            label: group.label
          };
        });
      }

      function calendarBands() {
        return {
          years: groupCalendarBands(
            function (date) { return String(date.getFullYear()); },
            function (date) { return String(date.getFullYear()); }
          ),
          months: groupCalendarBands(
            function (date) { return date.getFullYear() + '-' + date.getMonth(); },
            function (date) { return MONTHS_SHORT[date.getMonth()]; }
          )
        };
      }

      function buildCalendarDayCells(step) {
        const totalDays = active.scale.totalDays;
        const cells = [];
        const stride = typeof step === 'number' && step > 0 ? step : totalDays;

        for (let day = 0; day < totalDays; day += stride) {
          const endDay = Math.min(day + stride, totalDays);
          cells.push({
            start: day / totalDays,
            end: endDay / totalDays,
            label: String(dateAtDay(day).getDate())
          });
        }
        return cells;
      }

      function buildLinearCells(step) {
        const scale = active.scale;
        const span = scale.end - scale.start;
        const slots = 18;
        const stride = typeof step === 'number' && step > 0
          ? (span / slots) * step
          : span;
        const cells = [];

        for (let value = scale.start; value < scale.end - stride * 0.01; value += stride) {
          const end = Math.min(value + stride, scale.end);
          cells.push({
            start: eventFraction(value),
            end: eventFraction(end),
            label: scale.tickFormat(value)
          });
        }
        if (!cells.length || cells[cells.length - 1].end < 1 - 1e-9) {
          cells.push({
            start: cells.length ? cells[cells.length - 1].end : 0,
            end: 1,
            label: scale.tickFormat(scale.end)
          });
        } else {
          cells[cells.length - 1].end = 1;
        }
        return cells;
      }

      function buildLogCells(stride) {
        const scale = active.scale;
        const logMin = Math.log10(scale.tMin);
        const logMax = Math.log10(scale.tMax);
        const edges = [scale.tMin];

        if (Number.isFinite(stride) && stride > 0) {
          const startPow = Math.ceil(logMin + 1e-9);
          const endPow = Math.floor(logMax - 1e-9);
          for (let p = startPow; p <= endPow; p += stride) {
            const t = Math.pow(10, p);
            if (t > scale.tMin * 1.01 && t < scale.tMax * 0.99) edges.push(t);
          }
        }
        edges.push(scale.tMax);

        const cells = [];
        for (let i = 0; i < edges.length - 1; i++) {
          cells.push({
            start: eventFraction(edges[i]),
            end: eventFraction(edges[i + 1]),
            label: formatDuration(edges[i])
          });
        }
        return cells;
      }

      function buildEraCells() {
        return (active.scale.eras || []).map(function (era) {
          return {
            start: eventFraction(era.t0),
            end: eventFraction(era.t1),
            label: era.label
          };
        });
      }

      // Coarsen the numeric row until every label fits; fall back to the densest
      // packing if no whole resolution fits.
      function chooseNumericCells(usable) {
        if (active.scale.kind === 'log-seconds') {
          const strides = [1, 2, 4, 8, 16];
          let best = null;

          for (let i = 0; i < strides.length; i++) {
            const cells = buildLogCells(strides[i]);
            if (rowFits(cells, usable)) return cells;
            const packed = packCells(cells, usable);
            if (packed.length && (!best || packed.length > best.length)) best = packed;
          }
          return best;
        }

        let best = null;

        for (let i = 0; i < SCALE_NUMBER_STEPS.length; i++) {
          const step = SCALE_NUMBER_STEPS[i];
          const cells = active.scale.kind === 'calendar-days'
            ? buildCalendarDayCells(step === null ? active.scale.totalDays : step)
            : buildLinearCells(step === null ? 18 : step);

          if (rowFits(cells, usable)) return cells;
          const packed = packCells(cells, usable);
          if (packed.length && (!best || packed.length > best.length)) best = packed;
        }
        return best;
      }

      function buildScaleRows(usable) {
        const rows = [];

        if (active.scale.kind === 'calendar-days') {
          const bands = calendarBands();
          if (bands.years.length) rows.push({ key: 'year', cells: bands.years });
          if (bands.months.length) rows.push({ key: 'month', cells: bands.months });
        } else if (active.scale.kind === 'log-seconds') {
          const eras = buildEraCells();
          const eraRow = rowFits(eras, usable) ? eras : packCells(eras, usable);
          if (eraRow.length) rows.push({ key: 'era', cells: eraRow });
        } else {
          rows.push({
            key: 'period',
            cells: [{ start: 0, end: 1, label: active.scale.periodLabel }]
          });
        }

        const numeric = chooseNumericCells(usable);
        if (numeric && numeric.length) {
          rows.push({ key: 'numbers', cells: numeric });
        }

        // If coarser rows exist but numbers could not pack at all, keep coarser
        // rows only — unless nothing remains, then show the summary.
        if (!rows.length) {
          rows.push({
            key: 'summary',
            cells: [{ start: 0, end: 1, label: active.scale.summary, summary: true }]
          });
        }

        return rows;
      }

      function setScaleHeight(rowCount) {
        // 0 is valid: Hidden and In events area reserve no above-axis padding.
        const height = Math.max(rowCount, 0) * SCALE_ROW_HEIGHT;
        const px = height + 'px';
        timeline.style.setProperty('--scale-height', px);
        timelineWrapper.style.setProperty('--scale-height', px);
        timelineSlot.style.setProperty('--scale-height', px);
      }

      function layoutScaleGrid(attachLeft, reserve, usable, periodsPlacement) {
        const axisStart = attachLeft ? reserve : 0;

        scaleGrid.replaceChildren();
        scaleGrid.style.left = axisStart + 'px';
        scaleGrid.style.width = usable + 'px';
        scaleGrid.classList.toggle('is-hidden', periodsPlacement === 'hidden');
        scaleGrid.classList.toggle('is-in-events', periodsPlacement === 'events');

        if (periodsPlacement === 'hidden') {
          setScaleHeight(0);
          return 0;
        }

        /*
         * Cells are absolutely positioned inside the grid's frame, so they span
         * its padding box rather than its border box. Laying them out over
         * `usable` would push the last cell past the frame and give the
         * timeline a hairline of horizontal overflow.
         */
        const span = scaleGrid.clientWidth || usable;
        const rows = buildScaleRows(span);

        rows.forEach(function (row) {
          const rowEl = document.createElement('div');
          rowEl.className = 'scale-row';
          rowEl.dataset.scaleRow = row.key;

          row.cells.forEach(function (cell) {
            const cellEl = document.createElement('div');
            cellEl.className = 'scale-cell' + (cell.summary ? ' is-summary' : '');
            cellEl.style.left = (cell.start * span) + 'px';
            cellEl.style.width = Math.max((cell.end - cell.start) * span, 0) + 'px';
            // Only paint the label when it fits; the cell (and its line) remain.
            cellEl.textContent = cellFits(cell, span) ? cell.label : '';
            rowEl.appendChild(cellEl);
          });

          scaleGrid.appendChild(rowEl);
        });

        if (periodsPlacement === 'events') {
          // Above-axis padding is unused; the band lives inside the timeline.
          setScaleHeight(0);
          // 1px top offset under the axis + the painted grid (includes its border).
          return 1 + scaleGrid.offsetHeight;
        }

        setScaleHeight(rows.length);
        return 0;
      }

      function layout(settings) {
        const columnsKey = settings.columnsKey;
        const attachLeft = settings.attachLeft;
        const width = settings.width;
        const margin = settings.margin;
        const labelWidth = settings.labelWidth;
        const extendTimeline = settings.extendTimeline;
        const periodsPlacement = settings.periodsPlacement;

        const sideChanged = previousAttachLeft !== null && previousAttachLeft !== attachLeft;
        const contentChanged = previousDescs !== null && previousDescs !== columnsKey;
        const datasetChanged = previousDatasetId !== null && previousDatasetId !== active.id;
        const widthJumped = previousWidth !== null &&
          Math.abs(previousWidth - width) > MAX_RETAINED_WIDTH_DELTA;
        const labelWidthChanged = previousLabelWidth !== null &&
          previousLabelWidth !== labelWidth;
        const extendChanged = previousExtend !== null && previousExtend !== extendTimeline;
        const periodsChanged = previousPeriodsPlacement !== null &&
          previousPeriodsPlacement !== periodsPlacement;

        if (sideChanged || contentChanged || datasetChanged || widthJumped ||
            labelWidthChanged || extendChanged || periodsChanged) {
          stackRows.clear();
        }
        previousAttachLeft = attachLeft;
        previousDescs = columnsKey;
        previousWidth = width;
        previousLabelWidth = labelWidth;
        previousExtend = extendTimeline;
        previousPeriodsPlacement = periodsPlacement;
        previousDatasetId = active.id;

        timeline.style.width = width + 'px';
        controls.widthValue.textContent = width + 'px';

        const items = measureLabels(attachLeft, labelWidth);
        const widest = items.reduce(function (max, item) {
          return Math.max(max, item.width);
        }, 0);
        const baseReserve = Math.ceil(widest + RESERVE_PADDING);

        const minHairlineSpan = Math.max((items.length * 2) - 1, 1);
        const minTotal = minHairlineSpan + baseReserve + MIN_WIDTH_SLACK;
        if (width < minTotal) {
          timeline.style.width = minTotal + 'px';
        }

        const total = timeline.clientWidth;
        const reserve = extendTimeline
          ? fittedReserve(items, total, attachLeft, baseReserve)
          : baseReserve;
        timeline.style.setProperty('--text-reserve', reserve + 'px');

        const usable = Math.max(total - reserve, minHairlineSpan);

        positionHairlines(items, usable, attachLeft ? reserve : 0);
        controls.labelWidthValue.textContent = labelWidth + 'px';
        constrainLabelWidths(items, labelWidth);

        layoutAxis(reserve, attachLeft);
        const periodBand = layoutScaleGrid(attachLeft, reserve, usable, periodsPlacement);
        const labelBaseTop = BASE_TOP + periodBand;

        const maxBottom = stackLabels(items, attachLeft, margin, labelBaseTop);
        timeline.style.height = Math.max(MIN_TIMELINE_HEIGHT, maxBottom + HEIGHT_PADDING) + 'px';
      }

      function refresh() {
        try {
          const settings = readControls();
          renderLabels();
          void timeline.offsetHeight;
          layout(settings);
        } catch (err) {
          console.error('Timeline layout error:', err);
        }
      }

      function setControlsMinimised(minimised, moveFocus) {
        controlsPanel.classList.toggle('dock-hidden', minimised);
        flagsFab.classList.toggle('dock-hidden', !minimised);
        minimiseControls.setAttribute('aria-expanded', String(!minimised));
        flagsFab.setAttribute('aria-expanded', String(!minimised));

        try {
          localStorage.setItem(CONTROLS_MINIMISED_KEY, minimised ? '1' : '0');
        } catch (err) {
          /* storage unavailable — state is session-only */
        }

        if (moveFocus) {
          (minimised ? flagsFab : minimiseControls).focus();
        }
      }

      function start() {
        if (!PLAYGROUND) document.body.classList.remove('playground');

        loadDatasetsFromDom();
        loadDataset(selectedDatasetId());
        refresh();

        if (window.ResizeObserver) {
          new ResizeObserver(function () { refresh(); }).observe(timeline.parentElement);
        } else {
          window.addEventListener('resize', refresh);
        }
        window.addEventListener('load', refresh);

        document.querySelectorAll('.col-toggles input[data-col]').forEach(function (input) {
          input.addEventListener('change', function () {
            loadDataset(selectedDatasetId());
            requestAnimationFrame(refresh);
          });
        });

        if (!PLAYGROUND) return;

        let storedMinimised = null;
        try {
          storedMinimised = localStorage.getItem(CONTROLS_MINIMISED_KEY);
        } catch (err) {
          /* storage unavailable — start expanded */
        }
        setControlsMinimised(storedMinimised === '1', false);
        requestAnimationFrame(function () {
          document.body.classList.add('dock-animated');
        });

        minimiseControls.addEventListener('click', function () {
          setControlsMinimised(true, true);
        });

        flagsFab.addEventListener('click', function () {
          setControlsMinimised(false, true);
          requestAnimationFrame(refresh);
        });

        datasetRadios.forEach(function (radio) {
          radio.addEventListener('change', function () {
            loadDataset(radio.value);
            requestAnimationFrame(refresh);
          });
        });

        [
          [controls.attachSide, 'change'],
          [controls.fullWidth, 'change'],
          [controls.labelWidth, 'input'],
          [controls.extendTimeline, 'change'],
          [controls.periodsPlacement, 'change']
        ].forEach(function (pair) {
          pair[0].addEventListener(pair[1], function () {
            requestAnimationFrame(refresh);
          });
        });

        controls.width.addEventListener('input', function () {
          if (controls.fullWidth.checked) {
            controls.fullWidth.checked = false;
            controls.width.disabled = false;
          }
          requestAnimationFrame(refresh);
        });
      }

      start();
    })();
